INSERT INTO ALUNO (DATA_NASCIMENTO) VALUE (VARCHAR(10) NOT NULL);

ALTER TABLE ALUNO CHANGE COLUMN TELEFONE CONTATO VARCHAR(45) NOT NULL;

INSERT INTO LIVRO (ISBN) VALUE (VARCHAR (13));

DROP TABLE ISBN;
