ALUNO = SELECT NOTA > 7,0;

ALUNO = SELECT (SÉRIE = '1°ano').and.(NOTA >= 8,0;

ALUNO = PROJECT (P.NOME, NOTA);

CREATE TABLE PROFESSOR(
    P.NOME VARCHAR(50),
    U.NOME VARCHAR(100),
);

CREATE TABLE ALUNO(
    P.NOME VARCHAR(50),
    U.NOME VARCHAR(100),
);

ALUNO UNION PROFESSOR;

ALUNO INTERSECT PROFESSOR;

ALUNO <> PROFESSOR;


