ALUNO = SELECT NOTA > FLOAT(7.0);

ALUNO = SELECT (SÉRIE = '1°ano').and.(NOTA >= FLOAT(8.0);

ALUNO = PROJECT (P.NOME, NOTA);

CREATE TABLE PROFESSOR(
    P.NOME VARCHAR(50),
    U.NOME VARCHAR(100),
);

CREATE TABLE ALUNO(
    P.NOME VARCHAR(50),
    U.NOME VARCHAR(100),
);

ALUNO UNION PROFESSOR;

ALUNO INTERSECT PROFESSOR;

SELECT * FROM ALUNO WHERE PROFESSOR NOT IN(SELECT * FROM PROFESSOR);


